### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by ugintl** [GitzJoey/DCSLab#131]
I think you should change the name because it is confusing. When I opened the repo, I thought it was some kind of online laboratory.

**Comment by GitzJoey** [comment]
well, thanks for the input.
honestly this is actually a "lab" for us, to build something,

**Comment by ugintl** [comment]
@GitzJoey What should I call it? A crm?

**Comment by GitzJoey** [comment]
@ugintl u can call anything u want bro, but as for us, we just stick with it for now
