### ISSUE TITLE
create unique code validation on update

### ISSUE THREAD

**Issue by HugoYaw22** [GitzJoey/DCSLab#54]
bikin unique code utk table : 	
-> companies (ok)
-> branches
-> warehouses
-> product_groups
-> product_brand
-> product_units
-> products
-> cashes (ok)
-> suppliers
-> customer_groups
-> customers

**Comment by Hartanto119** [comment]
> 
> 
> bikin unique code utk table :
> -> companies (ok)
> -> branches (ok)
> -> warehouses
> -> product_groups
> -> product_brand
> -> product_units
> -> products
> -> cashes (ok)
> -> suppliers
> -> customer_groups
> -> customers
