### ISSUE TITLE
fix header grid

### ISSUE THREAD

**Issue by HugoYaw22** [GitzJoey/DCSLab#55]
-> companies
-> branches
-> warehouses
-> product_groups
-> product_brand
-> product_units
-> products
-> cashes
-> suppliers
-> customer_groups
-> customers

**Comment by Hartanto119** [comment]
> 
> 
> -> companies (ok)
> -> branches (ok)
> -> warehouses
> -> product_groups
> -> product_brand
> -> product_units
> -> products
> -> cashes
> -> suppliers
> -> customer_groups
> -> customers
