### ISSUE TITLE
product

### ISSUE THREAD

**Issue by HugoYaw22** [GitzJoey/DCSLab#88]
kolom Group Name ga tampil saat show
kolom Brand Name ga tampil saat show
kolom Unit Name ga tampil saat show
kolom Product Type ga tampil saat show

**Comment by Hartanto119** [comment]
kolom Group Name ga tampil saat show (done)
kolom Brand Name ga tampil saat show (done)
kolom Unit Name ga tampil saat show (done)
kolom Product Type ga tampil saat show (done)
